### PR TITLE
Use hatch for tests/builds instead of tox

### PR DESCRIPTION
**Pull request by 0xDEC0DE**
This change is [Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)

### CODE REVIEW

**Review by 0xDEC0DE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: 0 of 22 files reviewed, 1 unresolved discussion

___
*[`.github/workflows/tests.yml` line 12 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbVsPJcBTBgsy4azLRJ:-NbVsPJcBTBgsy4azLRK:be73zo2) ([raw file](https://github.com/juledwar/soufi/blob/0e63548bcf40c21ed23b94720cade56d897a181a/.github/workflows/tests.yml#L12)):*
> ```YAML
>     strategy:
>       matrix:
>         python-version: ['3.8', '3.9', '3.10', '3.11']
> ```

Funny story: In YAML the numeric literal `3.10` is equivalent to `3.1`.  Fucking YAML...

**Review by juledwar — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: all files reviewed, 2 unresolved discussions (waiting on @0xDEC0DE)

___
*[`MANIFEST.in` line 9 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbWhcp438oz-nQacpYP:-NbWhcp50I9hiFYmg1iw:b-fluawu) ([raw file](https://github.com/juledwar/soufi/blob/5c74049bf64e9182c6675eb3c27db61a913ddc6f/MANIFEST.in#L9)):*
> ```
> prune tools
> exclude .*
> prune .*
> ```

I don't think this should be deleted? It controls the sdist content.

**Review by juledwar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: all files reviewed, 1 unresolved discussion (waiting on @0xDEC0DE)

**Review by 0xDEC0DE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: all files reviewed, 1 unresolved discussion (waiting on @juledwar)

___
*[`MANIFEST.in` line 9 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbWhcp438oz-nQacpYP:-NbWlnOG22Mj5LDoKKg-:b-b37937) ([raw file](https://github.com/juledwar/soufi/blob/5c74049bf64e9182c6675eb3c27db61a913ddc6f/MANIFEST.in#L9)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

I don't think this should be deleted? It controls the sdist content.
</blockquote></details>

It didn't seem to, the build directives in `pyproject.toml` seemed to do all of that.

**Comment by juledwar** [comment]
*[`MANIFEST.in` line 9 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbWhcp438oz-nQacpYP:-NbWm2Ab3TmlrfzsA-7e:bddckxm) ([raw file](https://github.com/juledwar/soufi/blob/5c74049bf64e9182c6675eb3c27db61a913ddc6f/MANIFEST.in#L9)):*
<details><summary><i>Previously, 0xDEC0DE (Nicolas Simonds) wrote…</i></summary><blockquote>

It didn't seem to, the build directives in `pyproject.toml` seemed to do all of that.
</blockquote></details>

Huh. We still have in in helios.

**Review by 0xDEC0DE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: all files reviewed, 1 unresolved discussion (waiting on @juledwar)

___
*[`MANIFEST.in` line 9 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbWhcp438oz-nQacpYP:-NbWnSvI6fWI1hWrZcTd:bclyklx) ([raw file](https://github.com/juledwar/soufi/blob/5c74049bf64e9182c6675eb3c27db61a913ddc6f/MANIFEST.in#L9)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

Huh. We still have in in helios.
</blockquote></details>

I'm not 100% sure it's needed there, either.

**Comment by juledwar** [comment]
*[`MANIFEST.in` line 9 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbWhcp438oz-nQacpYP:-NbWneD7-OlKshTmLGlj:bpew8bh) ([raw file](https://github.com/juledwar/soufi/blob/5c74049bf64e9182c6675eb3c27db61a913ddc6f/MANIFEST.in#L9)):*
<details><summary><i>Previously, 0xDEC0DE (Nicolas Simonds) wrote…</i></summary><blockquote>

I'm not 100% sure it's needed there, either.
</blockquote></details>

Can you humour me and do a build to see if the sdist looks ok?

**Review by 0xDEC0DE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: all files reviewed, 1 unresolved discussion (waiting on @juledwar)

___
*[`MANIFEST.in` line 9 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbWhcp438oz-nQacpYP:-NbWo6JTCXlRxsxLiPDn:b-780xqj) ([raw file](https://github.com/juledwar/soufi/blob/5c74049bf64e9182c6675eb3c27db61a913ddc6f/MANIFEST.in#L9)):*
<details><summary><i>Previously, juledwar (Julian Edwards) wrote…</i></summary><blockquote>

Can you humour me and do a build to see if the sdist looks ok?
</blockquote></details>

Here are the build artifacts I made to prove it out:



_Code snippet:_
```
$ tar tvzf dist/soufi-2022.6.8.dev3+g5c74049.d20230810.tar.gz
-rw-r--r--  0 0      0        9406 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/__init__.py
-rw-r--r--  0 0      0         220 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/_version.py
-rw-r--r--  0 0      0         686 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/exceptions.py
-rw-r--r--  0 0      0       10993 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finder.py
-rw-r--r--  0 0      0        9530 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/alpine.py
-rw-r--r--  0 0      0        5225 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/centos.py
-rw-r--r--  0 0      0        3292 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/debian.py
-rw-r--r--  0 0      0        1277 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/gem.py
-rw-r--r--  0 0      0        1708 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/golang.py
-rw-r--r--  0 0      0        2380 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/java.py
-rw-r--r--  0 0      0        1249 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/npm.py
-rw-r--r--  0 0      0        2738 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/photon.py
-rw-r--r--  0 0      0        2908 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/python.py
-rw-r--r--  0 0      0        1439 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/rhel.py
-rw-r--r--  0 0      0        2927 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/ubuntu.py
-rw-r--r--  0 0      0       13036 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/finders/yum.py
-rw-r--r--  0 0      0           0 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/functional/__init__.py
-rw-r--r--  0 0      0       10558 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/functional/test_functional.py
-rw-r--r--  0 0      0           0 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/__init__.py
-rw-r--r--  0 0      0        3611 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/base.py
-rw-r--r--  0 0      0        4377 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/factory.py
-rw-r--r--  0 0      0        5308 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/community/go/APKBUILD
-rw-r--r--  0 0      0         818 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/community/py3-alembic/APKBUILD
-rw-r--r--  0 0      0        4700 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/dbus/0001-_dbus_generate_random_bytes-use-getrandom-2.patch
-rw-r--r--  0 0      0        2720 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/dbus/APKBUILD
-rw-r--r--  0 0      0         644 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/dbus/avoid-opendir-between-fork-exec.patch
-rw-r--r--  0 0      0         906 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/dbus/dbus.initd
-rw-r--r--  0 0      0          54 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/dbus/dbus.post-install
-rw-r--r--  0 0      0         152 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/dbus/dbus.pre-install
-rw-r--r--  0 0      0         137 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/dbus/dbus.trigger
-rw-r--r--  0 0      0       28116 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/gcc/APKBUILD
-rw-r--r--  0 0      0        1014 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/gdbm/APKBUILD
-rw-r--r--  0 0      0        2303 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/java-gcj-compat/APKBUILD
-rw-r--r--  0 0      0        1047 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/lua-gversion/APKBUILD
-rw-r--r--  0 0      0        3553 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/lua5.2/APKBUILD
-rw-r--r--  0 0      0        2038 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/lua5.2/lua-5.2-make.patch
-rw-r--r--  0 0      0        1024 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/lua5.2/lua-5.2-module_paths.patch
-rw-r--r--  0 0      0        3619 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/openssl/APKBUILD
-rw-r--r--  0 0      0        2777 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/openssl/man-section.patch
-rw-r--r--  0 0      0        3297 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/openssl/ppc64.patch
-rw-r--r--  0 0      0        1278 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/perl-posix-strftime-compiler/APKBUILD
-rw-r--r--  0 0      0        2271 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/testing/data/aports/main/xorgproto/APKBUILD
-rw-r--r--  0 0      0         390 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/__init__.py
-rw-r--r--  0 0      0        1290 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/test_factory.py
-rw-r--r--  0 0      0        8403 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/test_finder_base.py
-rw-r--r--  0 0      0           0 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/__init__.py
-rw-r--r--  0 0      0       13200 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_alpine_finder.py
-rw-r--r--  0 0      0        9083 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_centos_finder.py
-rw-r--r--  0 0      0        8264 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_debian_finder.py
-rw-r--r--  0 0      0        2309 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_gem_finder.py
-rw-r--r--  0 0      0        2843 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_golang_finder.py
-rw-r--r--  0 0      0        4170 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_java_finder.py
-rw-r--r--  0 0      0        2444 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_npm_finder.py
-rw-r--r--  0 0      0       10330 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_photon_finder.py
-rw-r--r--  0 0      0        4240 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_python_finder.py
-rw-r--r--  0 0      0        1745 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_rhel_finder.py
-rw-r--r--  0 0      0        5733 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_ubuntu_finder.py
-rw-r--r--  0 0      0       21294 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/soufi/tests/finders/test_yum_finder.py
-rw-r--r--  0 0      0         970 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/.gitignore
-rw-r--r--  0 0      0         265 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/AUTHORS
-rw-r--r--  0 0      0       10784 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/LICENCE.txt
-rw-r--r--  0 0      0        3085 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/README.rst
-rw-r--r--  0 0      0        5346 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/pyproject.toml
-rw-r--r--  0 0      0        5029 Feb  1  2020 soufi-2022.6.8.dev3+g5c74049.d20230810/PKG-INFO

$ unzip -l dist/soufi-2022.6.8.dev3+g5c74049.d20230810-py2.py3-none-any.whl
Archive:  dist/soufi-2022.6.8.dev3+g5c74049.d20230810-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
     9406  02-02-2020 00:00   soufi/__init__.py
      220  02-02-2020 00:00   soufi/_version.py
      686  02-02-2020 00:00   soufi/exceptions.py
    10993  02-02-2020 00:00   soufi/finder.py
     9530  02-02-2020 00:00   soufi/finders/alpine.py
     5225  02-02-2020 00:00   soufi/finders/centos.py
     3292  02-02-2020 00:00   soufi/finders/debian.py
     1277  02-02-2020 00:00   soufi/finders/gem.py
     1708  02-02-2020 00:00   soufi/finders/golang.py
     2380  02-02-2020 00:00   soufi/finders/java.py
     1249  02-02-2020 00:00   soufi/finders/npm.py
     2738  02-02-2020 00:00   soufi/finders/photon.py
     2908  02-02-2020 00:00   soufi/finders/python.py
     1439  02-02-2020 00:00   soufi/finders/rhel.py
     2927  02-02-2020 00:00   soufi/finders/ubuntu.py
    13036  02-02-2020 00:00   soufi/finders/yum.py
     5029  02-02-2020 00:00   soufi-2022.6.8.dev3+g5c74049.d20230810.dist-info/METADATA
      105  02-02-2020 00:00   soufi-2022.6.8.dev3+g5c74049.d20230810.dist-info/WHEEL
       37  02-02-2020 00:00   soufi-2022.6.8.dev3+g5c74049.d20230810.dist-info/entry_points.txt
      265  02-02-2020 00:00   soufi-2022.6.8.dev3+g5c74049.d20230810.dist-info/licenses/AUTHORS
    10784  02-02-2020 00:00   soufi-2022.6.8.dev3+g5c74049.d20230810.dist-info/licenses/LICENCE.txt
     1893  02-02-2020 00:00   soufi-2022.6.8.dev3+g5c74049.d20230810.dist-info/RECORD
---------                     -------
    87127                     22 files
```

**Review by 0xDEC0DE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: all files reviewed, 1 unresolved discussion (waiting on @juledwar)

___
*[`MANIFEST.in` line 9 at r1](https://reviewable.io/reviews/juledwar/soufi/35#-NbWhcp438oz-nQacpYP:-NbWoYH5A4SfSpJIrCFI:b-ipd1os) ([raw file](https://github.com/juledwar/soufi/blob/5c74049bf64e9182c6675eb3c27db61a913ddc6f/MANIFEST.in#L9)):*
<details><summary><i>Previously, 0xDEC0DE (Nicolas Simonds) wrote…</i></summary><blockquote>

Here are the build artifacts I made to prove it out:
</blockquote></details>

..and yes, since the sdist is supposed to be the original sources, I include all the tests.  The wheel has them properly filtered out.

**Review by juledwar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/juledwar/soufi/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0xDEC0DE)

**Pull request merged**
